<a href="https://colab.research.google.com/github/praut05/Github/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:
import pandas as pd
import numpy as np

In [95]:
df = pd.read_csv('data.csv')

In [96]:
df.sample(10)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
455,9112085,B,13.380,30.72,86.34,557.2,0.09245,0.07426,0.028190,0.032640,...,41.61,96.69,705.6,0.1172,0.14210,0.070030,0.07763,0.2196,0.07675,NaN
276,8911230,B,11.330,14.16,71.79,396.6,0.09379,0.03872,0.001487,0.003333,...,18.99,77.37,458.0,0.1259,0.07348,0.004955,0.01111,0.2758,0.06386,NaN
182,873701,M,15.700,20.31,101.20,766.6,0.09597,0.08799,0.065930,0.051890,...,32.82,129.30,1269.0,0.1414,0.35470,0.290200,0.15410,0.3437,0.08631,NaN
61,858981,B,8.598,20.98,54.66,221.8,0.12430,0.08963,0.030000,0.009259,...,27.04,62.06,273.9,0.1639,0.16980,0.090010,0.02778,0.2972,0.07712,NaN
442,90944601,B,13.780,15.79,88.37,585.9,0.08817,0.06718,0.010550,0.009937,...,17.50,97.90,706.6,0.1072,0.10710,0.035170,0.03312,0.1859,0.06810,NaN
372,9012795,M,21.370,15.10,141.30,1386.0,0.10010,0.15150,0.193200,0.125500,...,21.84,152.10,1535.0,0.1192,0.28400,0.402400,0.19660,0.2730,0.08666,NaN
327,895299,B,12.030,17.93,76.09,446.0,0.07683,0.03892,0.001546,0.005592,...,22.25,82.74,523.4,0.1013,0.07390,0.007732,0.02796,0.2171,0.07037,NaN
560,925292,B,14.050,27.15,91.38,600.4,0.09929,0.11260,0.044620,0.043040,...,33.17,100.20,706.7,0.1241,0.22640,0.132600,0.10480,0.2250,0.08321,NaN
540,921385,B,11.540,14.44,74.65,402.9,0.09984,0.11200,0.067370,0.025940,...,19.68,78.78,457.8,0.1345,0.21180,0.179700,0.06918,0.2329,0.08134,NaN
453,911201,B,14.530,13.98,93.86,644.2,0.10990,0.09242,0.068950,0.064950,...,16.93,103.10,749.9,0.1347,0.14780,0.137300,0.10690,0.2606,0.07810,NaN

In [97]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [98]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [99]:
df.shape

(569, 31)

In [100]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=2)

In [101]:
X_train.shape

(455, 30)

In [102]:
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()

X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [103]:
X_train

array([[-0.01330339,  1.7757658 , -0.01491962, ..., -0.13236958,
        -1.08014517, -0.03527943],
       [-0.8448276 , -0.6284278 , -0.87702746, ..., -1.11552632,
        -0.85773964, -0.72098905],
       [ 1.44755936,  0.71180168,  1.47428816, ...,  0.87583964,
         0.4967602 ,  0.46321706],
       ...,
       [-0.46608541, -1.49375484, -0.53234924, ..., -1.32388956,
        -1.02997851, -0.75145272],
       [-0.50025764, -1.62161319, -0.527814  , ..., -0.0987626 ,
         0.35796577, -0.43906159],
       [ 0.96060511,  1.21181916,  1.00427242, ...,  0.8956983 ,
        -1.23064515,  0.50697397]])

In [114]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

In [115]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [116]:
from sklearn.metrics import accuracy_score
y_pred=knn.predict(X_test)
accuracy_score(y_test,y_pred)

0.9736842105263158

In [117]:
y_train.unique()

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [118]:
X = df.iloc[:,1:]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier

for i in range(1,21):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    y_pred = knn.predict(X_test)
    print(i, accuracy_score(y_test,y_pred))

1 0.956140350877193
2 0.9736842105263158
3 0.9912280701754386
4 0.9736842105263158
5 0.9736842105263158
6 0.9736842105263158
7 0.9736842105263158
8 0.9736842105263158
9 0.9736842105263158
10 0.9736842105263158
11 0.9736842105263158
12 0.9736842105263158
13 0.9736842105263158
14 0.9649122807017544
15 0.9649122807017544
16 0.9649122807017544
17 0.9649122807017544
18 0.9649122807017544
19 0.9649122807017544
20 0.9649122807017544