<a href="https://colab.research.google.com/github/praut05/Github/blob/main/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('play_tennis.csv')
df.drop(columns=['day'],inplace = True)

In [ ]:
df.sample(10)

     outlook  temp humidity    wind play
8      Sunny  Cool   Normal    Weak  Yes
7      Sunny  Mild     High    Weak   No
12  Overcast   Hot   Normal    Weak  Yes
1      Sunny   Hot     High  Strong   No
10     Sunny  Mild   Normal  Strong  Yes
6   Overcast  Cool   Normal  Strong  Yes
5       Rain  Cool   Normal  Strong   No
2   Overcast   Hot     High    Weak  Yes
0      Sunny   Hot     High    Weak   No
13      Rain  Mild     High  Strong   No

**Problem 1**

Outlook = Sunny ,
Temp = Hot ,
Humidity = High ,
Wind = Weak
Play or No play?

**Solution**

P(Yes | Sunny,Hot,High,Weak) = P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes) * P(Yes)

P(No | Sunny,Hot,High,Weak) = P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No) * P(No)


Compare both and decide which one is high

In [ ]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [ ]:
pY=9/14
pN=5/14

In [ ]:
print(pY)
print(pN)

0.6428571428571429
0.35714285714285715

In [ ]:
#Outlook
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [ ]:
PON=0   #Probability of Overcast NO(PON)
PRN=2/5 #Probability of Rain NO(PRN)
PSN=3/5 #Probability of Sunny NO(PSN)

POY = 4/9 #Probability of Overcast YES(POY)
PRY = 3/9 #Probability of Rain YES(PRY)
PSY = 2/9 #Probability of Sunny YES(PSY)

In [ ]:
#Temp
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [ ]:
PCN=1/5 #Probability of Cool NO(PCN)
PHN=2/5 ##Probability of Hot NO(PHN)
PMN=2/5 #Probability of Mild NO(PMN)

PYC=3/9 #Probability of Cool YES(PYC)
PHY=2/9 #Probability of Hot YES(PHY)
PMY=4/9 #Probability of Mild YES(PMY)

In [ ]:
#Humidity
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [ ]:
PNH = 4/5 #Probability of High NO(PHN)
PNN = 1/5 #Probability of Normal NO(PNN)

PYH = 3/9 #Probability of High YES(PYH)
PNY = 6/9 #Probability of Normal YES(

In [ ]:
#Wind
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [ ]:
PNS=3/5 #Probability of Strong NO(PNS)
PNW=2/5 #Probability of Weak NO(PNW)

PYS=3/9 #Probability of Strong YES(PYW)
PYW=6/9 #Probability of Weak YES(

In [ ]:
#Outlook = Sunny , Temp = Hot , Humidity = High , Wind = Weak Play or No play?
pYes = pY*PSY*PHY*PYH*PYW
print(pYes)

0.007054673721340388

In [ ]:
pNo = pN*PSN*PHN*PNH*PNW
print(pNo)

0.05485714285714286

In [ ]:
# No play